project:
  type: website
  output-dir: docs

website:
  title: "Engineering Bytes"
  site-url: https://nishantbharali.github.io/Blog/
  description: "Nishant Bharali's engineering blog"
  open-graph: true
  cookie-consent: true
  twitter-card: 
    image: images/Nishant.jpg
    card-style: summary_large_image
    creator: "@NishantBharali"
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/nishant-kumar-bharali/
        target: _blank
        text: LinkedIn
      - icon: github
        href: https://github.com/NishantBharali
        target: _blank
        text: GitHub
      - icon: stack-overflow
        href: https://stackoverflow.com/users/18371927/nishant
        target: _blank
        text: Stack Overflow
      - icon: envelope
        href: mailto:nishantkb@vt.edu
        text: Gmail
      - icon: file-earmark-person
        href: Resume2.pdf
        text: Resume
      - text: Blog
        href: blog.qmd
      - text: Resources
        menu:
          - text: "Nishant's Resources"
            href: resources.qmd
          - text: Python for Data Science
            href: https://r4ds.hadley.nz/
            target: _blank
          - text: Tidyverse
            href: https://www.tidyverse.org/
            target: _blank
          - text: Tidymodels
            href: https://www.tidymodels.org/
            target: _blank
          - text: Tidyverse Style Guide
            href: https://style.tidyverse.org/
            target: _blank
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap

webr: 
  show-startup-message: false
  show-header-message: false
  channel-type: 'post-message'

execute:
  freeze: true
  cache: true